### ISSUE TITLE
Problem with files starting with escapable characters on Windows 

### ISSUE THREAD

**Issue by stro** [Perl-Toolchain-Gang/File-ShareDir-Install#3]
I found this problem while trying to build recent Plack on Windows. 
Here are test failures for Plack: http://matrix.cpantesters.org/?dist=Plack%201.0044;os=mswin32;perl=5.26.0;reports=1

Basically, the problem here is based on usage of File::Spec (that use backslashes on Windows systems) for Makefiles (that uses forward slashes regardless of the system). If the first character is escapable (in Plack's case, it's "#"), then File::ShareDir::Install will generate incorrect Makefile. A Plack's example is the following:

```
# --- MakeMaker postamble section:
config::
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e "pm_to_blib({@ARGV}, '$(INST_LIB)')" -- \
	  share\#foo $(INST_LIB)\auto\share\dist\$(DISTNAME)\#foo \
	  share\baybridge.jpg $(INST_LIB)\auto\share\dist\$(DISTNAME)\baybridge.jpg \
	  share\face.jpg $(INST_LIB)\auto\share\dist\$(DISTNAME)\face.jpg 
```

As you can see, "share\\#foo" becomes "share#foo". 

There are two ways how this can be fixed: 
1. Replace backslashes with forward slashes on Windows systems. That would make Makefiles more consistent. 
or 
2. Escape backslashes, probably for Windows systems only too.

**Comment by karenetheridge** [comment]
closed via commits 08776785 and aa95e5ceb7. I will release this shortly.
