### ISSUE TITLE
Can't find dist file when INSTALL_BASE is used with ExtUtils::MakeMaker

### ISSUE THREAD

**Issue by fluks** [Perl-Toolchain-Gang/File-ShareDir-Install#6]
If I install using INSTALL_BASE, dist_file can't find the files where they were copied to. I attached a simple test case and I run the commands:

```
perl Makefile.PL INSTALL_BASE=test && make && make install && perl test/bin/t.pl
```
And I get an error:
```
Failed to find share dir for dist 't' at test/bin/t.pl line 5.
```
If I install as a root without INSTALL_BASE, the file is found.

[test.tar.gz](https://github.com/Perl-Toolchain-Gang/File-ShareDir-Install/files/5765473/test.tar.gz)

**Comment by Leont** [comment]
It can't find any of the library files either, because you haven't told perl where to find the library files (but I'm guessing that's not obvious because either you're not loading any library files, or you're loading old ones).

`perl -Itest/lib/perl5 test/bin/t.pl` should get you further

**Comment by fluks** [comment]
Of course. Thanks for your help.
